// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220501193139_7")]
    partial class _7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Phone1Verified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4150),
                            Email = "User1@teste.com",
                            Name = "User1",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4140)
                        },
                        new
                        {
                            Id = 2,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4152),
                            Email = "User2@teste.com",
                            Name = "User2",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4151)
                        },
                        new
                        {
                            Id = 3,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4153),
                            Email = "User3@teste.com",
                            Name = "User3",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422"
                        },
                        new
                        {
                            Id = 4,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4155),
                            Email = "User4@teste.com",
                            Name = "User4",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422"
                        },
                        new
                        {
                            Id = 5,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4157),
                            Email = "User5@teste.com",
                            Name = "User5",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4155)
                        },
                        new
                        {
                            Id = 6,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4158),
                            Email = "User6@teste.com",
                            Name = "User6",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4157)
                        },
                        new
                        {
                            Id = 7,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4161),
                            Email = "User7@teste.com",
                            Name = "User7",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4159)
                        },
                        new
                        {
                            Id = 8,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4162),
                            Email = "User8@teste.com",
                            Name = "User8",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4161)
                        },
                        new
                        {
                            Id = 9,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4164),
                            Email = "User9@teste.com",
                            Name = "User9",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4163)
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Area 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Area 2"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Base.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Key1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUse")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantityMaxUse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantityMaxUseUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Regulation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UseLimiteDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4231),
                            Description = "Cupom 1 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4222),
                            PartnerId = 1,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4221),
                            Title = "Cupom 1",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4228)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4236),
                            Description = "Cupom 2 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4235),
                            PartnerId = 1,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 5,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4234),
                            Title = "Cupom 2",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4235)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4239),
                            Description = "Cupom 3 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4238),
                            PartnerId = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4237),
                            Title = "Cupom 3",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4239)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4243),
                            Description = "Cupom 4 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4241),
                            PartnerId = 2,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4241),
                            Title = "Cupom 4",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4242)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4246),
                            Description = "Cupom 5 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 29, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4244),
                            PartnerId = 2,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4244),
                            Title = "Cupom 5",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4245)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4250),
                            Description = "Cupom 6 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 29, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4248),
                            PartnerId = 2,
                            QuantityMaxUse = 50,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4247),
                            Title = "Cupom 6",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4248)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4253),
                            Description = "Cupom 7 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 29, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4251),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4250),
                            Title = "Cupom 7",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4252)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4256),
                            Description = "Cupom 8 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4254),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4253),
                            Title = "Cupom 8",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4255)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4259),
                            Description = "Cupom 9 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4257),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4257),
                            Title = "Cupom 9",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4258)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4262),
                            Description = "Cupom 10 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4261),
                            PartnerId = 4,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4260),
                            Title = "Cupom 10",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4261)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4265),
                            Description = "Cupom 11 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4264),
                            PartnerId = 4,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4263),
                            Title = "Cupom 11",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4264)
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CouponId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("coupons_participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4285),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4286),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 3,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4287),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 4,
                            CouponId = 2,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4289),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 5,
                            CouponId = 3,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4321),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 6,
                            CouponId = 4,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4323),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 7,
                            CouponId = 5,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4324),
                            ParticipantId = 1
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CouponId");

                    b.ToTable("coupons_users", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "123456",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4111),
                            District = "Bairro",
                            Email = "Participant1@teste.com",
                            Name = "Participant1",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "1234567",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4115),
                            District = "Bairro",
                            Email = "Participant2@teste.com",
                            Name = "Participant2",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "1234568",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4117),
                            District = "Bairro",
                            Email = "Participant3@teste.com",
                            Name = "Participant3",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "12345699",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4118),
                            District = "Bairro",
                            Email = "Participant4@teste.com",
                            Name = "Participant4",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.ParticipantUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("AccountId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("participants_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4191),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4193),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4194),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4196),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4197),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 6,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4198),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 7,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4199),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 8,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4200),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 9,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4201),
                            ParticipantId = 3
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Regulation")
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("SegmentId");

                    b.ToTable("partners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Teresina",
                            Cnpj = "123456",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(3643),
                            District = "Bairro",
                            Email = "Empresa1@teste.com",
                            Name = "Empresa1",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 2,
                            City = "Teresina",
                            Cnpj = "1234567",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(3662),
                            District = "Bairro",
                            Email = "Empresa2@teste.com",
                            Name = "Empresa2",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 3,
                            City = "Teresina",
                            Cnpj = "1234568",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(3664),
                            District = "Bairro",
                            Email = "Empresa3@teste.com",
                            Name = "Empresa3",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 4,
                            City = "Teresina",
                            Cnpj = "12345699",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 31, 12, 190, DateTimeKind.Local).AddTicks(4082),
                            District = "Bairro",
                            Email = "Empresa4@teste.com",
                            Name = "Empresa4",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("segments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Segmento 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Segmento 2"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.OwnsMany("WebApi.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReasonRevoked")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Token")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Account")
                                .HasForeignKey("AccountId");

                            b1.Navigation("Account");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Base.Event", b =>
                {
                    b.HasOne("WebApi.Entities.Core.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Coupon", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponParticipant", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponUser", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Participant", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WebApi.Entities.Core.ParticipantUser", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Partner", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });
#pragma warning restore 612, 618
        }
    }
}
