// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220501191138_6")]
    partial class _6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Phone1Verified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3124),
                            Email = "User1@teste.com",
                            Name = "User1",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3096)
                        },
                        new
                        {
                            Id = 2,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3138),
                            Email = "User2@teste.com",
                            Name = "User2",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3128)
                        },
                        new
                        {
                            Id = 3,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3143),
                            Email = "User3@teste.com",
                            Name = "User3",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422"
                        },
                        new
                        {
                            Id = 4,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3148),
                            Email = "User4@teste.com",
                            Name = "User4",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422"
                        },
                        new
                        {
                            Id = 5,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3157),
                            Email = "User5@teste.com",
                            Name = "User5",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3151)
                        },
                        new
                        {
                            Id = 6,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3165),
                            Email = "User6@teste.com",
                            Name = "User6",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3159)
                        },
                        new
                        {
                            Id = 7,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3174),
                            Email = "User7@teste.com",
                            Name = "User7",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3168)
                        },
                        new
                        {
                            Id = 8,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3183),
                            Email = "User8@teste.com",
                            Name = "User8",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3177)
                        },
                        new
                        {
                            Id = 9,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3191),
                            Email = "User9@teste.com",
                            Name = "User9",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3186)
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Area 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Area 2"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Base.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Key1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUse")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantityMaxUse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantityMaxUseUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Regulation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tile")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UseLimiteDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3546),
                            Description = "Cupom 1 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3394),
                            PartnerId = 1,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3392),
                            Tile = "Cupom 1",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3406)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3565),
                            Description = "Cupom 2 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3560),
                            PartnerId = 1,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 5,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3558),
                            Tile = "Cupom 2",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3562)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3578),
                            Description = "Cupom 3 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3570),
                            PartnerId = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3568),
                            Tile = "Cupom 3",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3575)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3588),
                            Description = "Cupom 4 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3582),
                            PartnerId = 2,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3580),
                            Tile = "Cupom 4",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3584)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3600),
                            Description = "Cupom 5 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 29, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3594),
                            PartnerId = 2,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3592),
                            Tile = "Cupom 5",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3596)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3612),
                            Description = "Cupom 6 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 29, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3605),
                            PartnerId = 2,
                            QuantityMaxUse = 50,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3604),
                            Tile = "Cupom 6",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3608)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3625),
                            Description = "Cupom 7 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 29, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3619),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3617),
                            Tile = "Cupom 7",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3621)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4004),
                            Description = "Cupom 8 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3630),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3629),
                            Tile = "Cupom 8",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3632)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4019),
                            Description = "Cupom 9 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4010),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4008),
                            Tile = "Cupom 9",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4013)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4030),
                            Description = "Cupom 10 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4025),
                            PartnerId = 4,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4023),
                            Tile = "Cupom 10",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4026)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4039),
                            Description = "Cupom 11 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 6, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4034),
                            PartnerId = 4,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4033),
                            Tile = "Cupom 11",
                            UseLimiteDate = new DateTime(2022, 5, 16, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4036)
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CouponId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("coupons_participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4267),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4272),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 3,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4275),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 4,
                            CouponId = 2,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4278),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 5,
                            CouponId = 3,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4281),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 6,
                            CouponId = 4,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4284),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 7,
                            CouponId = 5,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(4287),
                            ParticipantId = 1
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CouponId");

                    b.ToTable("coupons_users", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "123456",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(2983),
                            District = "Bairro",
                            Email = "Participant1@teste.com",
                            Name = "Participant1",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "1234567",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(2997),
                            District = "Bairro",
                            Email = "Participant2@teste.com",
                            Name = "Participant2",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "1234568",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3002),
                            District = "Bairro",
                            Email = "Participant3@teste.com",
                            Name = "Participant3",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "12345699",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3007),
                            District = "Bairro",
                            Email = "Participant4@teste.com",
                            Name = "Participant4",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.ParticipantUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("AccountId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("participants_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3284),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3290),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3294),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3297),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3300),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 6,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3303),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 7,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3306),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 8,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3308),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 9,
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(3312),
                            ParticipantId = 3
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Regulation")
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("SegmentId");

                    b.ToTable("partners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Teresina",
                            Cnpj = "123456",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(2836),
                            District = "Bairro",
                            Email = "Empresa1@teste.com",
                            Name = "Empresa1",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 2,
                            City = "Teresina",
                            Cnpj = "1234567",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(2881),
                            District = "Bairro",
                            Email = "Empresa2@teste.com",
                            Name = "Empresa2",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 3,
                            City = "Teresina",
                            Cnpj = "1234568",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(2886),
                            District = "Bairro",
                            Email = "Empresa3@teste.com",
                            Name = "Empresa3",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 4,
                            City = "Teresina",
                            Cnpj = "12345699",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 5, 1, 16, 11, 10, 302, DateTimeKind.Local).AddTicks(2891),
                            District = "Bairro",
                            Email = "Empresa4@teste.com",
                            Name = "Empresa4",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("segments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Segmento 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Segmento 2"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.OwnsMany("WebApi.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReasonRevoked")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Token")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Account")
                                .HasForeignKey("AccountId");

                            b1.Navigation("Account");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Base.Event", b =>
                {
                    b.HasOne("WebApi.Entities.Core.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Coupon", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponParticipant", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponUser", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Participant", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WebApi.Entities.Core.ParticipantUser", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Partner", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });
#pragma warning restore 612, 618
        }
    }
}
