// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220430182207_5")]
    partial class _5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Phone1Verified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1886),
                            Email = "User1@teste.com",
                            Name = "User1",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1874)
                        },
                        new
                        {
                            Id = 2,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1890),
                            Email = "User2@teste.com",
                            Name = "User2",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1887)
                        },
                        new
                        {
                            Id = 3,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1892),
                            Email = "User3@teste.com",
                            Name = "User3",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422"
                        },
                        new
                        {
                            Id = 4,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1895),
                            Email = "User4@teste.com",
                            Name = "User4",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422"
                        },
                        new
                        {
                            Id = 5,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1898),
                            Email = "User5@teste.com",
                            Name = "User5",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1896)
                        },
                        new
                        {
                            Id = 6,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1901),
                            Email = "User6@teste.com",
                            Name = "User6",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1899)
                        },
                        new
                        {
                            Id = 7,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1905),
                            Email = "User7@teste.com",
                            Name = "User7",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1902)
                        },
                        new
                        {
                            Id = 8,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1908),
                            Email = "User8@teste.com",
                            Name = "User8",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1906)
                        },
                        new
                        {
                            Id = 9,
                            AcceptTerms = true,
                            Created = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1911),
                            Email = "User9@teste.com",
                            Name = "User9",
                            PasswordHash = "$2a$11$jurHlZ3Jf1AOIrkKMLcsBueo0JYM8mWVCi6w4QTE9Rx1yKJC2WV/q",
                            Role = 0,
                            VerificationToken = "583422",
                            Verified = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1909)
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Area 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Area 2"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Base.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Key1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUse")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantityMaxUse")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantityMaxUseUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Regulation")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UseLimiteDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.ToTable("coupons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2090),
                            Description = "Cupom 1 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 5, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2079),
                            PartnerId = 1,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2078),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2087)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2101),
                            Description = "Cupom 2 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 5, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2098),
                            PartnerId = 1,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 5,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2097),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2099)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2107),
                            Description = "Cupom 3 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2104),
                            PartnerId = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2103),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2105)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2112),
                            Description = "Cupom 4 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2109),
                            PartnerId = 2,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2109),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2111)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2118),
                            Description = "Cupom 5 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 28, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2115),
                            PartnerId = 2,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2114),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2116)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2422),
                            Description = "Cupom 6 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 28, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2420),
                            PartnerId = 2,
                            QuantityMaxUse = 50,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2419),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2421)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2475),
                            Description = "Cupom 7 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 4, 28, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2472),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2471),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2473)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2480),
                            Description = "Cupom 8 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 5, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2478),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2477),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2479)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2489),
                            Description = "Cupom 9 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 5, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2483),
                            PartnerId = 3,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2482),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2484)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2494),
                            Description = "Cupom 10 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 5, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2492),
                            PartnerId = 4,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2491),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2493)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2499),
                            Description = "Cupom 11 - dewr rewrr rer",
                            FinishAt = new DateTime(2022, 5, 5, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2497),
                            PartnerId = 4,
                            QuantityMaxUse = 50,
                            QuantityMaxUseUser = 1,
                            QuantityUsed = 0,
                            Regulation = "Resulamento xx xx x x",
                            StartAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2496),
                            UseLimiteDate = new DateTime(2022, 5, 15, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2498)
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CouponId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("coupons_participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2542),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 2,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2545),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 3,
                            CouponId = 1,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2547),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 4,
                            CouponId = 2,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2549),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 5,
                            CouponId = 3,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2551),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 6,
                            CouponId = 4,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2552),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 7,
                            CouponId = 5,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2554),
                            ParticipantId = 1
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CouponId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CouponId");

                    b.ToTable("coupons_users", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.Core.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "123456",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1826),
                            District = "Bairro",
                            Email = "Participant1@teste.com",
                            Name = "Participant1",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "1234567",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1835),
                            District = "Bairro",
                            Email = "Participant2@teste.com",
                            Name = "Participant2",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "1234568",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1839),
                            District = "Bairro",
                            Email = "Participant3@teste.com",
                            Name = "Participant3",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 1,
                            City = "Teresina",
                            Cnpj = "12345699",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1841),
                            District = "Bairro",
                            Email = "Participant4@teste.com",
                            Name = "Participant4",
                            Phone1 = "Phone1",
                            PostalCode = "64014050",
                            State = "PI",
                            Street = "Rua X"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.ParticipantUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("AccountId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("participants_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2025),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2028),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2030),
                            ParticipantId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2032),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2033),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 6,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2035),
                            ParticipantId = 2
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 7,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2037),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 8,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2039),
                            ParticipantId = 3
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 9,
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(2041),
                            ParticipantId = 3
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Regulation")
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("SegmentId");

                    b.ToTable("partners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Teresina",
                            Cnpj = "123456",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1748),
                            District = "Bairro",
                            Email = "Empresa1@teste.com",
                            Name = "Empresa1",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 2,
                            City = "Teresina",
                            Cnpj = "1234567",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1778),
                            District = "Bairro",
                            Email = "Empresa2@teste.com",
                            Name = "Empresa2",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 3,
                            City = "Teresina",
                            Cnpj = "1234568",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1780),
                            District = "Bairro",
                            Email = "Empresa3@teste.com",
                            Name = "Empresa3",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        },
                        new
                        {
                            Id = 4,
                            City = "Teresina",
                            Cnpj = "12345699",
                            Contact = "Contato",
                            CreatedAt = new DateTime(2022, 4, 30, 15, 21, 45, 781, DateTimeKind.Local).AddTicks(1783),
                            District = "Bairro",
                            Email = "Empresa4@teste.com",
                            Name = "Empresa4",
                            Phone1 = "Phone1",
                            PictureUrl = "https://random.imagecdn.app/500/150",
                            PostalCode = "64014050",
                            SegmentId = 1,
                            State = "PI",
                            Street = "Rua X"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Core.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("segments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Segmento 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Segmento 2"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Account", b =>
                {
                    b.OwnsMany("WebApi.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReasonRevoked")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Token")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Account")
                                .HasForeignKey("AccountId");

                            b1.Navigation("Account");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Base.Event", b =>
                {
                    b.HasOne("WebApi.Entities.Core.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Coupon", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponParticipant", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WebApi.Entities.Core.CouponUser", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Participant", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WebApi.Entities.Core.ParticipantUser", b =>
                {
                    b.HasOne("WebApi.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Entities.Core.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("WebApi.Entities.Core.Partner", b =>
                {
                    b.HasOne("WebApi.Entities.Core.Segment", "Segment")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });
#pragma warning restore 612, 618
        }
    }
}
